version: '3.7'

services:
  php-fpm:
    container_name: cals_hereus_garage
    build:
      context: images/php
    ports:
      - "9000:80"
      - "5173:5173" #vite dev server
    volumes:
      - ../:/var/www:delegated
    env_file:
      - ./../.env
    environment:
      WEB_DOCUMENT_ROOT: "/var/www/public"
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:8.0.23
    container_name: cals_hereus_garage_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: hereu
      MYSQL_PASSWORD: pepet123
      MYSQL_DATABASE: calshereus
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3366:3306"

volumes:
  database:
